recipes-demos: benchmark-demo: Fix QA Issue
- The benchmark-demo-firmware recipe installs the necessary firmwares
in ${base_libdir} of deploy directory.

- Hence, update the destination directory in copy command to fix the
following QA Issue observed while building the recipe.

```
ERROR: benchmark-demo-firmware-08_01_00_25-r0r1 do_package: QA Issue: benchmark-demo-firmware: Files/directories were installed but not shipped in any package:
  /lib
  /lib/firmware
  /lib/firmware/mcusdk-benchmark_demo
  /lib/firmware/mcusdk-benchmark_demo/am64-main-r5f0_0-fw
  /lib/firmware/mcusdk-benchmark_demo/am64-main-r5f1_0-fw
  /lib/firmware/mcusdk-benchmark_demo/am64-main-r5f1_1-fw
  /lib/firmware/mcusdk-benchmark_demo/am64-main-r5f0_1-fw
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
benchmark-demo-firmware: 7 installed and not shipped files. [installed-vs-shipped]
```

Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>