recipes-core: packagegroups: Drop references of purged components
* evse-hmi, protection-relays-hmi & mmwavegesture-hmi were a part
of meta-arago-demos which no longer exists [0]. Hence, drop references
of these components under meta-tisdk.

* This resolves following build failures observed with AM335x & AM437x
with meta-tisdk:scarthgap:HEAD,

```

ERROR: Nothing RPROVIDES 'evse-hmi-src' (but packagegroup-arago-tisdk-sourceipks-sdk-host.bb RDEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['evse-hmi-src']

ERROR: Nothing RPROVIDES 'protection-relays-hmi-src' (but packagegroup-arago-tisdk-sourceipks-sdk-host.bb RDEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['protection-relays-hmi-src']

ERROR: Nothing RPROVIDES 'mmwavegesture-hmi-src' (but packagegroup-arago-tisdk-sourceipks-sdk-host.bb RDEPENDS on or otherwise requires it)
Missing or unbuildable dependency chain was: ['mmwavegesture-hmi-src']

```

[0]: https://git.yoctoproject.org/meta-arago/commit/?h=scarthgap&id=3b605894553664a74e260bb305deab92e67f3983

Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>